version: '2'
services:
  rabbit:
    hostname: rabbit
    image: rabbitmq
    expose:
      - "5672"
      - "15672"
  

  sender:
    container_name: sender
    build: ./Server
    depends_on:
      - rabbit
    links:
      - rabbit


  client:
    container_name: client
    build: .
    depends_on: 
      - sender
    links:
      - sender

  client2:
    container_name: client2
    build: .
    depends_on: 
      - sender
    links:
      - sender
