version: "3"
services:
  servidor:
    container_name: ps_server
    hostname: SERVER
    command: python3 server.py
    environment:
      PYTHONUNBUFFERED: 1
    build:
      dockerfile: server/DF_SERVER
      context: .
    ports:
      - "50051:50051"
    network_mode: host

  cliente:
    container_name: ps_client
    hostname: CLIENT
    command: python3 client.py in
    # environment:
    #   PYTHONUNBUFFERED: 1
    build:
      dockerfile: client/DF_CLIENT
      context: .
    ports:
      - "50051:50051"
    network_mode: host
    depends_on: 
      - servidor
  
  cliente2:
    deploy:
      replicas: 2
    hostname: ps_client2
    command: python3 client.py in2
    # environment:
      # PYTHONUNBUFFERED: 1
    build:
      dockerfile: client/DF_CLIENT
      context: .
    ports:
      - "50051:50051"
    network_mode: host
    depends_on: 
      - servidor
      - cliente